### ISSUE TITLE
Errors about Tensorflow or theano? 

### ISSUE THREAD

**Issue by ClinuxMDL** [Shen-Lab/gcWGAN#2]
Dear developers,

When the backend is Tensorflow:
>CUDA_VISIBLE_DEVICES=0 python Nov_SeqGenerator_Filter_r1py3.py ./DeepSF_modified/DeepSF_model_weight_more_folds/model-train-weight-DLS2F.h5 ALL 100 test_generated_file_index test_job_index M_DeepSF

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/theano/tensor/type.py", line 270, in dtype_specs
    }[self.dtype]
KeyError: 'object'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/theano/tensor/basic.py", line 250, in constant_or_value
    TensorType(dtype=x_.dtype, broadcastable=bcastable),
  File "/usr/local/lib/python3.6/dist-packages/theano/tensor/type.py", line 51, in __init__
    self.dtype_specs()  # error checking is done there
  File "/usr/local/lib/python3.6/dist-packages/theano/tensor/type.py", line 273, in dtype_specs
    % (self.__class__.__name__, self.dtype))
TypeError: Unsupported dtype for TensorType: object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/theano/tensor/basic.py", line 206, in as_tensor_variable
    return constant(x, name=name, ndim=ndim)
  File "/usr/local/lib/python3.6/dist-packages/theano/tensor/basic.py", line 264, in constant
    dtype=dtype)
  File "/usr/local/lib/python3.6/dist-packages/theano/tensor/basic.py", line 259, in constant_or_value
    raise TypeError("Could not convert %s to TensorType" % x, type(x))
TypeError: ('Could not convert ? to TensorType', <class 'tensorflow.python.framework.tensor_shape.Dimension'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Nov_SeqGenerator_Filter_r1py3.py", line 142, in <module>
    M_DLS2F_CNN = model_from_json(M_loaded_model_json, custom_objects={'K_max_pooling1d': Oracle_Filters.K_max_pooling1d})
  File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 213, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/layer_utils.py", line 40, in layer_from_config
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 2582, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 2577, in process_layer
    layer(input_tensors[0])
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 572, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 635, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 166, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/root/projects/newFoldDesign/toolkits/gcWGAN/Oracle_py3/Oracle_Filters.py", line 296, in call
    output = x[T.arange(x.shape[0]).dimshuffle(0, "x", "x"),
  File "/usr/local/lib/python3.6/dist-packages/theano/tensor/basic.py", line 5396, in arange
    start, stop, step = map(as_tensor_variable, (start, stop, step))
  File "/usr/local/lib/python3.6/dist-packages/theano/tensor/basic.py", line 212, in as_tensor_variable
    raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
theano.tensor.var.AsTensorError: ('Cannot convert ? to TensorType', <class 'tensorflow.python.framework.tensor_shape.Dimension'>)

How could I hande this issue? modify theano type or T.arange? 

Thank you very much.

**Comment by Shaowen1994** [comment]
Dear user,

I think the issue may be that you used "tensorflow" as the backend of keras while "tensorflow" is only used for training gcWGAN. I have updated our Readme file and you may try to change the backend to "theano" according to the instruction. Please let me know if the issue is not solved or there can be any new issues arising. Thank you.

Best, 
Shaowen
